<?php

namespace Database\Seeders;

use App\Enums\GoodEnum;
use App\Enums\GoodTypeEnum;
use App\Models\Good;
use App\Models\GoodType;
use Illuminate\Database\Seeder;
use Illuminate\Http\UploadedFile;
use Orchid\Attachment\File;

class GoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Good::query()->delete();
        foreach ($this->goods() as $goodTypeName => $good) {
            $goodTypeId = GoodType::query()->where('name', '=', $goodTypeName)->firstOrFail()->id;

            foreach ($good as $key => $value) {
                $good = Good::query()->create([
                    'name_ru' => $value['name_ru'],
                    'name_en' => $value['name_en'],
                    'description_ru' => $value['description_ru'],
                    'description_en' => $value['description_en'],
                    'cost' => $value['cost'],
                    'damage_cost' => $value['damage_cost'],
                    'additionals' => Good::query()->whereIn('name_ru', $value['additionals'])->pluck('id'),
                    'good_type_id' => $goodTypeId,
                    'discount_cost' => null,
                    'additional_cost' => isset($value['additional_cost']) ? $value['additional_cost'] : $value['cost'],
                    'related_goods' => [],
                ]);

                if (! is_null($value['image'])) {
                    $file = new UploadedFile('resources/img/'.$value['image'], $value['image']);

                    $attachment = (new File($file))->load();

                    $good->attachment()->syncWithoutDetaching($attachment);
                }
            }
        }
    }

    public function goods(): array
    {
        return [
            GoodTypeEnum::CAMERAS->value => $this->cameras(),
            GoodTypeEnum::LENSES->value => $this->lenses(),
            GoodTypeEnum::LIGHT->value => $this->light(),
            GoodTypeEnum::SOUND->value => $this->sound(),
            GoodTypeEnum::STABILIZERS->value => $this->stabilizers(),
            GoodTypeEnum::BATTERIES->value => $this->batteries(),
            GoodTypeEnum::DRONES->value => $this->drones(),
            GoodTypeEnum::DATA_CARDS->value => $this->dataCards(),
            GoodTypeEnum::CAGES->value => $this->cages(),
            GoodTypeEnum::DISPLAYS->value => $this->displays(),
            GoodTypeEnum::MISCELLANEOUS->value => $this->miscellaneous(),
            GoodTypeEnum::SOFTBOXES->value => $this->softboxes(),
            GoodTypeEnum::FILTERS->value => $this->filters(),
            GoodTypeEnum::STANDS->value => $this->stands(),
            GoodTypeEnum::KITS->value => $this->kits(),
        ];
    }

    public function cameras(): array
    {
        return [
            GoodEnum::CINEMA_CAMERA_SONY_FX6->name => [
                'name_ru' => GoodEnum::CINEMA_CAMERA_SONY_FX6->value,
                'name_en' => 'Sony FX6 Cinema Camera',
                'cost' => 40000,
                'damage_cost' => 3000000,
                'description_ru' => '-SONY FX6 (Fullframe) -Sony bp battery, -Ручка с монитором',
                'description_en' => '-SONY FX6 (Fullframe) -Sony bp battery, -Handle with monitor',
                'additionals' => [
                    'SmallRig 99wh v mount',
                    'SWIT BP 220WH',
                    'Tilta V mount',
                    'CF Tough 160gb',
                ],
                'image' => '5.png',
            ],
            GoodEnum::CINEMA_CAMERA_BLACKMAGIC_6K_PRO->name => [
                'name_ru' => GoodEnum::CINEMA_CAMERA_BLACKMAGIC_6K_PRO->value,
                'name_en' => 'Blackmagic 6k pro cinema camera',
                'cost' => 16500,
                'damage_cost' => 1350000,
                'description_ru' => '-Blackmagic 6k pro (super 35) -NP-F570',
                'description_en' => '-Blackmagic 6k pro (super 35) -NP-F570',
                'additionals' => [
                    'SSD Samsung T7 1Tb',
                    'Объектив Sigma 18-35mm f1.8',
                    'Объектив Samyang VDSLR',
                    'Tilta + v mount',
                    'SmallRig 99wh',
                ],
                'image' => '18.png',
            ],
            GoodEnum::CINEMA_CAMERA_SONY_FX3->name => [
                'name_ru' => GoodEnum::CINEMA_CAMERA_SONY_FX3->value,
                'name_en' => 'Sony Fx3 Cinema Camera',
                'cost' => 23000,
                'damage_cost' => 2000000,
                'description_ru' => '-Sony FX3 (Fullframe) -Аккумулятор NPF Z100',
                'description_en' => '-Sony FX3 (Fullframe) -NPF Z100 Battery',
                'additionals' => [
                    'CF Tough 80gb',
                    'Карта памяти 256gb sony 277mbs',
                    'Tilta advanced cage',
                    'Доп аккумулятор NPF Z100',
                ],
                'image' => '7.png',
            ],
            GoodEnum::CINEMA_CAMERA_SONY_FX30->name => [
                'name_ru' => GoodEnum::CINEMA_CAMERA_SONY_FX30->value,
                'name_en' => 'Sony Fx30 Cinema Camera',
                'cost' => 11500,
                'damage_cost' => 1000000,
                'description_ru' => '-Sony FX-30 (APC) -Аккумулятор NPF Z100',
                'description_en' => '-Sony FX-30 (APC) -NPF Z100 battery',
                'additionals' => [
                    'CF Tough 80gb',
                    'Карта памяти 256gb sony 277mbs',
                    'Tilta advanced cage',
                    'Доп аккумулятор NPF Z100',
                ],
                'image' => '8.png',

            ],
            GoodEnum::PHOTO_CAMERA_CANON_R7->name => [
                'name_ru' => GoodEnum::PHOTO_CAMERA_CANON_R7->value,
                'name_en' => 'Canon R7 camera',
                'cost' => 10000,
                'damage_cost' => 700000,
                'description_ru' => '-Canon R7 (APC) -Аккумулятор LP-E6N',
                'description_en' => '-Canon R7 (APC) -Battery LP-E6N',
                'additionals' => [
                    'Переходник RF-EF',
                    'Карта памяти Sandisk 64gb 200mbs',
                    'Объектив Canon RF 24-105mm f4-7.1',
                    'Дополнительный аккумулятор',
                ],
                'image' => '15.png',

            ],
            GoodEnum::PHOTO_CAMERA_CANON_R->name => [
                'name_ru' => GoodEnum::PHOTO_CAMERA_CANON_R->value,
                'name_en' => 'Canon R camera',
                'cost' => 10000,
                'damage_cost' => 700000,
                'description_ru' => '-Canon R (Fullframe) -Аккумулятор LP-E6N',
                'description_en' => '-Canon R (Fullframe) -Battery LP-E6N',
                'additionals' => [
                    'Переходник RF-EF',
                    'Карта памяти Sandisk 64gb 200mbs',
                    'Объектив Canon RF 24-105mm f4-7.1',
                    'Дополнительный аккумулятор',
                ],
                'image' => '16.png',

            ],
            GoodEnum::PHOTO_CAMERA_SONY_A7_III->name => [
                'name_ru' => GoodEnum::PHOTO_CAMERA_SONY_A7_III->value,
                'name_en' => 'Sony A7 III camera',
                'cost' => 10000,
                'damage_cost' => 750000,
                'description_ru' => '-Sony A7 III (Fullframe) -Аккумулятор NPF Z100',
                'description_en' => '-Sony A7 III (Fullframe) -NPF Z100 battery',
                'additionals' => [
                    'Карта памяти Sandisk 64gb 200mbs',
                    'Kit объектив 28-70mm oss f3.5-5.6',
                    'Клетка A7 III с рукояткой UURig',
                    'Дополнительный аккумулятор',
                ],
                'image' => '4.png',
            ],
            GoodEnum::PHOTO_CAMERA_SONY_A7C->name => [
                'name_ru' => GoodEnum::PHOTO_CAMERA_SONY_A7C->value,
                'name_en' => 'Sony A7C camera',
                'cost' => 10000,
                'damage_cost' => 750000,
                'description_ru' => '-Sony A7 С (Fullframe) -Аккумулятор NPF Z100',
                'description_en' => '-Sony A7 C (Fullframe) -NPF Z100 battery',
                'additionals' => [
                    'Карта памяти Sandisk 64gb 200mbs',
                    'Kit объектив 28-70mm oss f3.5-5.6',
                    'Клетка A7c',
                    'Дополнительный аккумулятор',
                ],
                'image' => '10.png',
            ],
            GoodEnum::PHOTO_CAMERA_SONY_A7_IV->name => [
                'name_ru' => GoodEnum::PHOTO_CAMERA_SONY_A7_IV->value,
                'name_en' => 'Sony A7 IV camera',
                'cost' => 12500,
                'damage_cost' => 120000,
                'description_ru' => '-Sony A7 IV (Fullframe) -Аккумулятор NPF Z100',
                'description_en' => '-Sony A7 IV (Fullframe) -NPF Z100 Battery',
                'additionals' => [
                    'Карта памяти Sandisk 64gb 200mbs',
                    'Kit объектив 28-70mm oss f3.5-5.6',
                    'Клетка Sony a7 IV',
                    'Дополнительный аккумулятор',
                ],
                'image' => '9.png',
            ],
            GoodEnum::PHOTO_CAMERA_SONY_A6600->name => [
                'name_ru' => GoodEnum::PHOTO_CAMERA_SONY_A6600->value,
                'name_en' => 'Sony A6600 camera',
                'cost' => 8000,
                'damage_cost' => 650000,
                'description_ru' => '-Sony A6600 (APC) -Аккумулятор NPF Z100',
                'description_en' => '-Sony A6600 (APC) -NPF Z100 battery',
                'additionals' => [
                    'Карта памяти Sandisk 64gb 200mbs',
                    'Kit объектив 18-135mm f3.5-5.6',
                    'Клетка a6600',
                    'Дополнительный аккумулятор',
                ],
                'image' => '12.png',
            ],
            GoodEnum::PHOTO_CAMERA_SONY_A6400->name => [
                'name_ru' => GoodEnum::PHOTO_CAMERA_SONY_A6400->value,
                'name_en' => 'Sony A6400 camera',
                'cost' => 5500,
                'damage_cost' => 500000,
                'description_ru' => '-Sony A6400 (APC) -Аккумулятор NPF Z100',
                'description_en' => '-Sony A6400 (APC) -NPF Z100 battery',
                'additionals' => [
                    'Карта памяти Sandisk 64gb 200mbs',
                    'Kit объектив 18-135mm f3.5-5.6',
                    'Клетка a6400',
                    'Дополнительный аккумулятор',
                ],
                'image' => '11.png',
            ],
            GoodEnum::PHOTO_CAMERA_FUJIFILM_T4->name => [
                'name_ru' => GoodEnum::PHOTO_CAMERA_FUJIFILM_T4->value,
                'name_en' => 'Fujifilm T4 camera',
                'cost' => 10000,
                'damage_cost' => 500000,
                'description_ru' => '-Fujifilm T4 (APC) -Аккумулятор NP-W235',
                'description_en' => '-Fujifilm T4 (APC) -Battery NP-W235',
                'additionals' => [
                    'Карта памяти Sandisk 64gb 200mbs',
                    'Kit Fujifilm 18-55mm f2.8-4',
                    'Клетка Fujifilm T4',
                    'Дополнительный аккумулятор',
                ],
                'image' => '14.png',
            ],
            GoodEnum::PHOTO_CAMERA_FUJIFILM_T3->name => [
                'name_ru' => GoodEnum::PHOTO_CAMERA_FUJIFILM_T3->value,
                'name_en' => 'Fujifilm T3 camera',
                'cost' => 6000,
                'damage_cost' => 600000,
                'description_ru' => '-Fujifilm T3 (APC) -Аккумулятор W126',
                'description_en' => '-Fujifilm T3 (APC) -Battery W126',
                'additionals' => [
                    'Карта памяти Sandisk 64gb 200mbs',
                    'Kit Fujifilm 18-55mm f2.8-4',
                    'Клетка Fujifilm T3',
                    'Дополнительный аккумулятор',
                ],
                'image' => '13.png',
            ],
            GoodEnum::ACTION_CAMERA_GO_PRO_11->name => [
                'name_ru' => GoodEnum::ACTION_CAMERA_GO_PRO_11->value,
                'name_en' => 'Go pro 11 action camera',
                'cost' => 9000,
                'damage_cost' => 200000,
                'description_ru' => '-Go pro 11 -Аккумулятор go pro 10-11',
                'description_en' => '-Go pro 11 -Battery go pro 10-11',
                'additionals' => [
                    'Карта памяти micro Sandisk 64gb 200mbs',
                    'Крепление на голову',
                    'Крепление на грудь',
                    'Крепление на машину',
                    'Аквабокс',
                    'Селфи палка',
                    'Дополнительный аккумулятор',
                ],
                'image' => '17.png',
            ],
        ];
    }

    public function lenses(): array
    {
        return [
            GoodEnum::OBJECTIVE_SONY_16_50MM_F3_5_5_6_OSS->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_16_50MM_F3_5_5_6_OSS,
                'name_en' => 'Sony 16-50mm f3.5-5.6 oss lens',
                'cost' => 2000,
                'damage_cost' => 100000,
                'description_ru' => 'Размер матрицы APSC Байонет Sony E Фокусное расстояние, мм 16−50 Светосила 3.5−5.6 Мин. дистанция фокусировки, м 0.25−0.3 Стабилизация изображения есть',
                'description_en' => 'APSC matrix size Sony E mount Focal length, mm 16−50 Aperture ratio 3.5−5.6 Min. focusing distance, m 0.25−0.3 Image stabilization yes',
                'additionals' => [],
                'image' => '36.png',
            ],
            GoodEnum::OBJECTIVE_SONY_28_70MM_F3_5_5_6_OSS->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_28_70MM_F3_5_5_6_OSS->value,
                'name_en' => 'Sony 28-70mm f3.5-5.6 oss lens',
                'cost' => 2000,
                'damage_cost' => 200000,
                'additional_cost' => 1000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E Фокусное расстояние, мм 28-70 Светосила 3.5-5.6 Мин. дистанция фокусировки, м 0.3-0.45 Стабилизация изображения есть',
                'description_en' => 'Matrix size Full frame Sony E mount Focal length, mm 28-70 Aperture 3.5-5.6 Min. focusing distance, m 0.3-0.45 Image stabilization yes',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::OBJECTIVE_SONY_28_60MM_F4_5_6_OSS->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_28_60MM_F4_5_6_OSS->value,
                'name_en' => 'Sony 28-60mm f4-5.6 oss lens',
                'cost' => 2000,
                'damage_cost' => 200000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E Фокусное расстояние, мм 28-70 Светосила 3.5-5.6 Мин. дистанция фокусировки, м 0.3-0.45 Стабилизация изображения есть',
                'description_en' => 'Matrix size Full frame Sony E mount Focal length, mm 28-70 Aperture 3.5-5.6 Min. focusing distance, m 0.3-0.45 Image stabilization yes',
                'additionals' => [],
                'image' => '35.png',
            ],
            GoodEnum::OBJECTIVE_SONY_ZEISS_24_70MM_F4_OSS->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_ZEISS_24_70MM_F4_OSS->value,
                'name_en' => 'Sony Zeiss 24-70mm f4 oss lens',
                'cost' => 3500,
                'damage_cost' => 300000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E Фокусное расстояние, мм 24−70 Светосила 4 Мин. дистанция фокусировки, м 0.38 Стабилизация изображения есть',
                'description_en' => 'Matrix size Full frame Sony E mount Focal length, mm 24−70 Aperture 4 Min. focusing distance, m 0.38 Image stabilization yes',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '34.png',
            ],
            GoodEnum::OBJECTIVE_SONY_85MM_GM_F1_4->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_85MM_GM_F1_4->value,
                'name_en' => 'Sony 85mm GM F1.4 Lens',
                'cost' => 10000,
                'damage_cost' => 700000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E Фокусное расстояние, мм 85 Светосила 1.4 Мин. дистанция фокусировки, м 0.85 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Sony E mount Focal length, mm 85 Aperture 1.4 Min. focusing distance, m 0.85 Image stabilization no',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '22.png',
            ],
            GoodEnum::OBJECTIVE_SONY_35MM_GM_F1_4->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_35MM_GM_F1_4->value,
                'name_en' => 'Sony 35mm GM F1.4 Lens',
                'cost' => 10000,
                'damage_cost' => 650000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E Фокусное расстояние, мм35 Светосила f1.4 Мин. дистанция фокусировки, м 0.26 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Sony E mount Focal length, mm35 Aperture f1.4 Min. focusing distance, m 0.26 Image stabilization no',
                'additionals' => [
                    'ND Filter Freewell 67mm',
                    'Tiffent mist Filter 67mm',
                ],
                'image' => '23.png',
            ],
            GoodEnum::OBJECTIVE_SONY_70_200_MM_GM_II_F2_8->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_70_200_MM_GM_II_F2_8,
                'name_en' => 'Sony 70-200 mm GM II F2.8 Lens',
                'cost' => 16500,
                'damage_cost' => 1200000,
                'description_ru' => 'Размер матрицы Full frame фокусное расстояние — 70−200 мм; диафрагма — f/2,8-f/22; минимальное расстояние фокусировки — 0,4 м; число лепестков диафрагмы — 11; длина — 200 мм; масса — 1045 г.',
                'description_en' => 'Matrix size Full frame focal length - 70−200 mm; aperture - f/2.8-f/22; minimum focusing distance - 0.4 m; number of aperture blades - 11; length - 200 mm; weight - 1045 g.',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '24.png',
            ],
            GoodEnum::OBJECTIVE_SONY_20MM_G_F1_8->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_20MM_G_F1_8->value,
                'name_en' => 'Sony 20mm G F1.8 Lens',
                'cost' => 6000,
                'damage_cost' => 450000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E Фокусное расстояние, мм 20 Светосила 1.8 Мин. дистанция фокусировки, м 0.18 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Sony E mount Focal length, mm 20 Aperture 1.8 Min. focusing distance, m 0.18 Image stabilization no',
                'additionals' => [
                    'ND Filter Freewell 67mm',
                    'Tiffent mist Filter 67mm',
                ],
                'image' => '21.png',
            ],
            GoodEnum::OBJECTIVE_SONY_18_105MM_G_F4->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_18_105MM_G_F4->value,
                'name_en' => 'Sony 18-105mm G F4 Lens',
                'cost' => 4000,
                'damage_cost' => 300000,
                'description_ru' => 'Размер матрицы APSC Байонет Sony E Фокусное расстояние, мм 18−105 Светосила 4 Мин. дистанция фокусировки, м 0.45−0.95',
                'description_en' => 'APSC matrix size Sony E mount Focal length, mm 18−105 Aperture 4 Min. focusing distance, m 0.45−0.95',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '25.png',
            ],
            GoodEnum::OBJECTIVE_SONY_18_135MM_F3_5_5_6->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_18_135MM_F3_5_5_6->value,
                'name_en' => 'Sony 18-135mm F3.5-5.6 lens',
                'cost' => 3500,
                'damage_cost' => 200000,
                'additional_cost' => 1500,
                'description_ru' => 'Размер матрицы — APSC Светосила — f3.5−5.6 Мин. дистанция фокусировки, м 0.45 Стабилизация изображения — есть',
                'description_en' => 'Matrix size - APSC Aperture - f3.5−5.6 Min. focusing distance, m 0.45 Image stabilization - yes',
                'additionals' => [
                    'ND Filter Freewell 67mm',
                    'Tiffent mist Filter 67mm',
                ],
                'image' => '118.png',
            ],
            GoodEnum::OBJECTIVE_SONY_50MM_F1_8->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SONY_50MM_F1_8->value,
                'name_en' => 'Sony 50mm F1.8 Lens',
                'cost' => 2500,
                'damage_cost' => 160000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E Фокусное расстояние, мм 50 Светосила 1.8 Мин. дистанция фокусировки, м 0.45 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Sony E mount Focal length, mm 50 Aperture 1.8 Min. focusing distance, m 0.45 Image stabilization no',
                'additionals' => [
                    'ND Filter Freewell 67mm',
                    'Tiffent mist Filter 67mm',
                ],
                'image' => '32.png',
            ],
            GoodEnum::OBJECTIVE_TAMRON_28_75MM_F2_8_RXD_SONY->name => [
                'name_ru' => GoodEnum::OBJECTIVE_TAMRON_28_75MM_F2_8_RXD_SONY->value,
                'name_en' => 'Tamron 28-75mm f2.8 RXD Sony Lens',
                'cost' => 6000,
                'damage_cost' => 400000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E Фокусное расстояние, мм 28-75 Светосила 2.8 Мин. дистанция фокусировки, м 0.34 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Sony E mount Focal length, mm 28-75 Aperture ratio 2.8 Min. focusing distance, m 0.34 Image stabilization no',
                'additionals' => [
                    'ND Filter Freewell 67mm',
                    'Tiffent mist Filter 67mm',
                ],
                'image' => '19.png',
            ],
            GoodEnum::OBJECTIVE_TAMRON_17_70MM_F2_8_RXD_SONY->name => [
                'name_ru' => GoodEnum::OBJECTIVE_TAMRON_17_70MM_F2_8_RXD_SONY->value,
                'name_en' => 'Tamron 17-70mm f2.8 RXD Sony Lens',
                'cost' => 6000,
                'damage_cost' => 400000,
                'description_ru' => 'Размер матрицы APC Байонет Sony E Фокусное расстояние, мм 17−70 Светосила 2.8 Мин. дистанция фокусировки, м 0.19 Стабилизация изображения нет',
                'description_en' => 'APC matrix size Sony E mount Focal length, mm 17−70 Aperture ratio 2.8 Min. focusing distance, m 0.19 Image stabilization no',
                'additionals' => [
                    'ND Filter Freewell 67mm',
                    'Tiffent mist Filter 67mm',
                ],
                'image' => '20.png',
            ],
            GoodEnum::OBJECTIVE_SIGMA_ART_24_70MM_F2_8_DG_DN_SONY->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SIGMA_ART_24_70MM_F2_8_DG_DN_SONY->value,
                'name_en' => 'Sigma Art 24-70mm f2.8 DG DN Sony Lens',
                'cost' => 8000,
                'damage_cost' => 500000,
                'description_ru' => 'Размер матрицы Full frame Байонет E mount Светосила f2.8 Минимальное расстояние фокусировки, м 0.18 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Mount E mount Aperture f2.8 Minimum focusing distance, m 0.18 Image stabilization no',
                'additionals' => [],
                'image' => '33.png',
            ],
            GoodEnum::OBJECTIVE_SIGMA_70MM_F2_8_DG_MACRO_SONY->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SIGMA_70MM_F2_8_DG_MACRO_SONY->value,
                'name_en' => 'Sigma 70mm f2.8 DG Macro Sony Lens',
                'cost' => 5500,
                'damage_cost' => 250000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E mount Фокусное расстояние, мм 70 Светосила 2.8 Мин. дистанция фокусировки, м 0.26 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Mount Sony E mount Focal length, mm 70 Aperture ratio 2.8 Min. focusing distance, m 0.26 Image stabilization no',
                'additionals' => [],
                'image' => '31.png',
            ],
            GoodEnum::OBJECTIVE_SIGMA_ART_16_28MM_F2_8_DG_DN_SONY->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SIGMA_ART_16_28MM_F2_8_DG_DN_SONY->value,
                'name_en' => 'Sigma Art 16-28mm f2.8 DG DN Sony Lens',
                'cost' => 6500,
                'damage_cost' => 400000,
                'description_ru' => 'Размер матрицы Full frame Байонет Sony E Фокусное расстояние, мм 16−28 Светосила 2.8 Мин. дистанция фокусировки, м 0.25 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Sony E mount Focal length, mm 16−28 Aperture ratio 2.8 Min. focusing distance, m 0.25 Image stabilization no',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '29.png',
            ],
            GoodEnum::OBJECTIVE_SIGMA_56MM_F1_4_DC_DN_SONY->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SIGMA_56MM_F1_4_DC_DN_SONY->value,
                'name_en' => 'Sigma 56mm f1.4 DC DN Sony Lens',
                'cost' => 3000,
                'damage_cost' => 200000,
                'description_ru' => 'Размер матрицы APSC Байонет Sony E Фокусное расстояние, мм 56 Светосила 1.4 Мин. дистанция фокусировки, м 0.5 Стабилизация изображения нет',
                'description_en' => 'APSC matrix size Sony E mount Focal length, mm 56 Aperture ratio 1.4 Min. focusing distance, m 0.5 Image stabilization no',
                'additionals' => [],
                'image' => '28.png',
            ],
            GoodEnum::OBJECTIVE_SIGMA_30MM_F1_4_DC_DN_SONY->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SIGMA_30MM_F1_4_DC_DN_SONY->value,
                'name_en' => 'Sigma 30mm f1.4 DC DN Sony Lens',
                'cost' => 3000,
                'damage_cost' => 200000,
                'description_ru' => 'Размер матрицы APSC Байонет Sony E Фокусное расстояние, мм 30 Светосила 1.4 Мин. дистанция фокусировки, м 0.3 Стабилизация изображения нет',
                'description_en' => 'APSC matrix size Sony E mount Focal length, mm 30 Aperture ratio 1.4 Min. focusing distance, m 0.3 Image stabilization no',
                'additionals' => [],
                'image' => '27.png',
            ],
            GoodEnum::OBJECTIVE_SIGMA_16MM_F1_4_DC_DN_SONY->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SIGMA_16MM_F1_4_DC_DN_SONY->value,
                'name_en' => 'Sigma 16mm f1.4 DC DN Sony Lens',
                'cost' => 3500,
                'damage_cost' => 200000,
                'description_ru' => 'Размер матрицы APSC Байонет Sony E Фокусное расстояние, мм 16 Светосила 1.4 Мин. дистанция фокусировки, м 0.25 Стабилизация изображения нет',
                'description_en' => 'APSC matrix size Sony E mount Focal length, mm 16 Aperture 1.4 Min. focusing distance, m 0.25 Image stabilization no',
                'additionals' => [
                    'ND Filter Freewell 67mm',
                    'Tiffent mist Filter 67mm',
                ],
                'image' => '26.png',
            ],
            GoodEnum::OBJECTIVE_SIRUI_50MM_F1_8_ANAMORPHIC_SONY->name => [
                'name_ru' => GoodEnum::OBJECTIVE_SIRUI_50MM_F1_8_ANAMORPHIC_SONY->value,
                'name_en' => 'Sirui 50mm f1.8 Anamorphic Sony Lens',
                'cost' => 5000,
                'damage_cost' => 250000,
                'description_ru' => 'Размер матрицы — APSC Байонет Sony E Светосила — f1.8 Стабилизация изображения — нет Анаморфотное искажение — 1.33',  'description_en' => 'Sensor size - APSC Sony E mount Aperture - f1.8 Image stabilization - no Anamorphic distortion - 1.33',  'additionals' => [],
                'image' => '115.png',
            ],
            GoodEnum::FUJINON_18_55MM->name => [
                'name_ru' => GoodEnum::FUJINON_18_55MM->value,
                'name_en' => 'Fujinon 18-55mm',
                'cost' => 3500,
                'damage_cost' => 200000,
                'additional_cost' => 1500,
                'description_ru' => 'Размер матрицы APSC Байонет Fujifilm X Фокусное расстояние, мм 18-55 Светосила 2.8-4..0 Мин. дистанция фокусировки, м 0.3 Стабилизация изображения есть',
                'description_en' => 'APSC matrix size Fujifilm X mount Focal length, mm 18-55 Aperture ratio 2.8-4..0 Min. focusing distance, m 0.3 Image stabilization yes',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '37.png',
            ],
            GoodEnum::CANON_RF_50MM_F1_8->name => [
                'name_ru' => GoodEnum::CANON_RF_50MM_F1_8->value,
                'name_en' => 'Canon RF 50mm f1.8',
                'cost' => 2500,
                'damage_cost' => 100000,
                'description_ru' => 'Размер матрицы Full frame Байонет Canon RF Фокусное расстояние, мм 50 Светосила 1.8 Мин. дистанция фокусировки, м 0.3 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Canon RF mount Focal length, mm 50 Aperture ratio 1.8 Min. focusing distance, m 0.3 Image stabilization no',
                'additionals' => [],
                'image' => '85.png',
            ],
            GoodEnum::CANON_RF_24_105_MM_F4_7_1->name => [
                'name_ru' => GoodEnum::CANON_RF_24_105_MM_F4_7_1->value,
                'name_en' => 'Canon RF 24-105 mm F4-7.1',
                'cost' => 3000,
                'damage_cost' => 200000,
                'additional_cost' => 2000,
                'description_ru' => 'Размер матрицы Full frame Байонет Canon RF Фокусное расстояние, мм 24−105 Светосила 4−7.1 Мин. дистанция фокусировки, м 0.34 Стабилизация изображения есть',
                'description_en' => 'Matrix size Full frame Canon RF mount Focal length, mm 24−105 Aperture ratio 4−7.1 Min. focusing distance, m 0.34 Image stabilization yes',
                'additionals' => [
                    'ND Filter Freewell 67mm',
                    'Tiffent mist Filter 67mm',
                ],
                'image' => '86.png',
            ],
            GoodEnum::SAMYANG_14MM_CANON->name => [
                'name_ru' => GoodEnum::SAMYANG_14MM_CANON->value,
                'name_en' => 'Samyang 14mm canon',
                'cost' => 5000,
                'damage_cost' => 250000,
                'additional_cost' => 3500,
                'description_ru' => 'Размер матрицы Full frame Байонет Canon EF Фокусное расстояние, мм 14 Светосила 2.8 Мин. дистанция фокусировки, м 0.28 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Canon EF mount Focal length, mm 14 Aperture 2.8 Min. focusing distance, m 0.28 Image stabilization no',
                'additionals' => [],
                'image' => '78.png',
            ],
            GoodEnum::SAMYANG_24MM_CANON->name => [
                'name_ru' => GoodEnum::SAMYANG_24MM_CANON->value,
                'name_en' => 'Samyang 24mm canon',
                'cost' => 5000,
                'damage_cost' => 250000,
                'description_ru' => 'Размер матрицы Full frame Байонет Canon EF Фокусное расстояние, мм 24 Светосила 1.5 Мин. дистанция фокусировки, м 0.25 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Canon EF mount Focal length, mm 24 Aperture 1.5 Min. focusing distance, m 0.25 Image stabilization no',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '77.png',
            ],
            GoodEnum::SAMYANG_135MM_CANON->name => [
                'name_ru' => GoodEnum::SAMYANG_135MM_CANON->value,
                'name_en' => 'Samyang 135mm canon',
                'cost' => 5000,
                'damage_cost' => 250000,
                'additional_cost' => 3500,
                'description_ru' => 'Размер матрицы Full frame Байонет Canon EF Фокусное расстояние, мм 135 Светосила 2.2 Мин. дистанция фокусировки, м 0.8 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Canon EF mount Focal length, mm 135 Aperture ratio 2.2 Min. focusing distance, m 0.8 Image stabilization no',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '79.png',
            ],
            GoodEnum::SAMYANG_85MM_CANON->name => [
                'name_ru' => GoodEnum::SAMYANG_85MM_CANON->value,
                'name_en' => 'Samyang 85mm canon',
                'cost' => 5000,
                'additional_cost' => 3500,
                'damage_cost' => 250000,
                'description_ru' => 'Размер матрицы Full frame Байонет Canon EF Фокусное расстояние, мм 85 Светосила 1.4 Мин. дистанция фокусировки, м 1 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Canon EF mount Focal length, mm 85 Aperture 1.4 Min. focusing distance, m 1 Image stabilization no',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '76.png',
            ],
            GoodEnum::SAMYANG_35MM_CANON->name => [
                'name_ru' => GoodEnum::SAMYANG_35MM_CANON->value,
                'name_en' => 'Samyang 35mm canon',
                'cost' => 5000,
                'additional_cost' => 3500,
                'damage_cost' => 250000,
                'description_ru' => 'Размер матрицы Full frame Байонет Canon EF Фокусное расстояние, мм 35 Светосила 1.5 Мин. дистанция фокусировки, м 0.3 Стабилизация изображения нет',
                'description_en' => 'Matrix size Full frame Canon EF mount Focal length, mm 35 Aperture 1.5 Min. focusing distance, m 0.3 Image stabilization no',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '81.png',
            ],
            GoodEnum::SIGMA_ART_18_35_MM_DC_CANON->name => [
                'name_ru' => GoodEnum::SIGMA_ART_18_35_MM_DC_CANON->value,
                'name_en' => 'Sigma art 18-35 mm Dc Canon',
                'cost' => 7000,
                'damage_cost' => 350000,
                'additional_cost' => 000,
                'description_ru' => 'Размер матрицы APSC Байонет Canon EF-S Фокусное расстояние, мм 18-35 Светосила 1.8 Мин. дистанция фокусировки, м 0.28 Стабилизация изображения есть',
                'description_en' => 'APSC matrix size Canon EF-S mount Focal length, mm 18-35 Aperture ratio 1.8 Min. focusing distance, m 0.28 Image stabilization yes',
                'additionals' => [
                    'ND Filter 77mm',
                ],
                'image' => '84.png',
            ],
            GoodEnum::SIGMA_ART_24_70MM_DG_CANON->name => [
                'name_ru' => GoodEnum::SIGMA_ART_24_70MM_DG_CANON->value,
                'name_en' => 'Sigma art 24-70mm DG Canon',
                'cost' => 10000,
                'damage_cost' => 600000,
                'description_ru' => 'Размер матрицы Full frame Байонет Canon EF Фокусное расстояние, мм 24-70 Светосила 2.8 Мин. дистанция фокусировки, м 0.37 Стабилизация изображения есть',
                'description_en' => 'Matrix size Full frame Canon EF mount Focal length, mm 24-70 Aperture ratio 2.8 Min. focusing distance, m 0.37 Image stabilization yes',
                'additionals' => [],
                'image' => '30.png',
            ],
        ];
    }

    private function light(): array
    {
        return [
            GoodEnum::APUTURE_300X->name => [
                'name_ru' => GoodEnum::APUTURE_300X->value,
                'name_en' => 'Aputure 300x',
                'cost' => 10000,
                'damage_cost' => 500000,
                'description_ru' => 'Мощность 350 ват Переменная CCT: от 2700 до 6500K',
                'description_en' => 'Power 350 watts Variable CCT: 2700 to 6500K',
                'additionals' => [
                    'Cтойка Godox 380',
                    'Софтбокс Lantern 90',
                    'Софтбокс Octadome 120',
                ],
                'image' => '106.png',

            ],
            GoodEnum::APUTURE_600X->name => [
                'name_ru' => GoodEnum::APUTURE_600X->value,
                'name_en' => 'Aputure 600x',
                'cost' => 15000,
                'damage_cost' => 900000,
                'description_ru' => 'Мощность 720 ват Переменная CCT: от 2700 до 6500K',
                'description_en' => 'Power 720 watts Variable CCT: 2700 to 6500K',
                'additionals' => [
                    'С-Stand',
                    'Софтбокс dome 150',
                ],
                'image' => '105.png',

            ],
            GoodEnum::APUTURE_NOVA_P300_KIT->name => [
                'name_ru' => GoodEnum::APUTURE_NOVA_P300_KIT->value,
                'name_en' => 'Aputure Nova p300 kit',
                'cost' => 14000,
                'damage_cost' => 800000,
                'additional_cost' => 1500,
                'description_ru' => 'Aputure Nova P300c — RGBWW. Большая панель мощностью 360 ват.',
                'description_en' => 'Aputure Nova P300c - RGBWW. Large 360 ​​watt panel.',
                'additionals' => [
                    'С-Stand',
                    'Cофтбокс P300',
                ],
                'image' => '110.png',

            ],
            GoodEnum::APUTURE_MC_RGBW_2->name => [
                'name_ru' => GoodEnum::APUTURE_MC_RGBW_2->value,
                'name_en' => 'Aputure Mc RGBW (2pcs)',
                'cost' => 2500,
                'damage_cost' => 50000,
                'description_ru' => 'Карманная панель RGBWW Bi-color: 3200K-6500K Мощность: 5 W Время автономной работы: 2 часа (максимальная яркость), 15 часов (минимальная яркость) Вес: 130 г Толщина: 17 мм',
                'description_en' => 'Pocket panel RGBWW Bi-color: 3200K-6500K Power: 5 W Battery life: 2 hours (maximum brightness), 15 hours (minimum brightness) Weight: 130 g Thickness: 17 mm',
                'additionals' => [],
                'image' => '112.png',
            ],
            GoodEnum::AMARAN_150C->name => [
                'name_ru' => GoodEnum::AMARAN_150C->value,
                'name_en' => 'Amaran 150c',
                'cost' => 6000,
                'damage_cost' => 200000,
                'description_ru' => 'CCT от 2500 до 7500K управление цветом HSI на 360° Мощность 150 вт',
                'description_en' => 'CCT from 2500 to 7500K color control HSI 360° Power 150 W',
                'additionals' => [
                    'Софтбокс Lantern',
                    'Софтбокс Octadome 120',
                    'Стойка',
                ],
                'image' => '41.png',
            ],
            GoodEnum::GODOX_SL200III->name => [
                'name_ru' => GoodEnum::GODOX_SL200III->value,
                'name_en' => 'Godox sl200III',
                'cost' => 7000,
                'damage_cost' => 175000,
                'description_ru' => 'Мощный источник дневного света, мощностью 200 ват, который поможет вам отснять качественные видео на Ютуб, Тикток и многое другое.',
                'description_en' => 'A powerful 200 watt daylight source that will help you shoot high-quality videos on YouTube, Tiktok and much more.',
                'additionals' => [
                    'Стойка',
                    'Софтбокс godox 60x60',
                ],
                'image' => '74.png',

            ],
            GoodEnum::GODOX_SL100BI->name => [
                'name_ru' => GoodEnum::GODOX_SL100BI->value,
                'name_en' => 'Godox sl100bi',
                'cost' => 4500,
                'damage_cost' => 100000,
                'description_ru' => 'Мощность 100 ват Переменная CCT: от 2700 до 6500K',
                'description_en' => 'Power 100 watts Variable CCT: 2700 to 6500K',
                'additionals' => [
                    'Стойка',
                    'Софтбокс godox 60x60',
                ],
                'image' => '73.png',
            ],
            GoodEnum::GODOX_AD300PRO->name => [
                'name_ru' => GoodEnum::GODOX_AD300PRO->value,
                'name_en' => 'Godox Ad300pro',
                'cost' => 6000,
                'damage_cost' => 250000,
                'description_ru' => 'Мощный моноблок на 300 Дж Встроенный приемник системы 2.4G X используется для дистанционного запуска и управления параметрами моноблока',
                'description_en' => 'Powerful 300 J all-in-one The built-in 2.4G X system receiver is used to remotely start and control the all-in-one parameters',
                'additionals' => [
                    'Стойка',
                    'Софтбокс godox 60x60',
                ],
                'image' => '75.png',

            ],
            GoodEnum::NANLITE_FORZA_60C->name => [
                'name_ru' => GoodEnum::NANLITE_FORZA_60C->value,
                'name_en' => 'Nanlite Forza 60c',
                'cost' => 6500,
                'damage_cost' => 300000,
                'description_ru' => 'Nanlite Forza 60C — прожектор RGBLAC CCT: 1800К-20000К Мощность: 88Вт Софтбокс входит в стоимость',
                'description_en' => 'Nanlite Forza 60C - RGBLAC CCT floodlight: 1800K-20000K Power: 88W Softbox included in price',
                'additionals' => [
                    'Стойка godox',
                    '2 аккумулятора NPF 970 для беспроводной зарядки',
                ],
                'image' => '102.png',

            ],
            GoodEnum::APUTURE_100X->name => [
                'name_ru' => GoodEnum::APUTURE_100X->value,
                'name_en' => 'Aputure 100x',
                'cost' => 5500,
                'damage_cost' => 150000,
                'description_ru' => 'Мощность 100 ват Переменная CCT: от 2700 до 6500K',
                'description_en' => 'Power 100 watts Variable CCT: 2700 to 6500K',
                'additionals' => [
                    'Стойка',
                    'Софтбокс godox 60x60',
                ],
                'image' => '104.png',

            ],
            GoodEnum::GODOX_TL60->name => [
                'name_ru' => GoodEnum::GODOX_TL60->value,
                'name_en' => 'Godox TL60',
                'cost' => 4000,
                'damage_cost' => 100000,
                'description_ru' => 'RGB Джедайка Регулировка цветовой температуры 2700К~6500К Время работы от батареи при полной мощности около 2 часов Длина 0.7 м',
                'description_en' => 'RGB Jediika Color temperature adjustment 2700K~6500K Battery life at full power about 2 hours Length 0.7 m',
                'additionals' => [
                    'Стойка',
                ],
                'image' => '68.png',
            ],
            GoodEnum::GODOX_V1_FLASH->name => [
                'name_ru' => GoodEnum::GODOX_V1_FLASH->value,
                'name_en' => 'Godox V1 Flash',
                'cost' => 3500,
                'damage_cost' => 110000,
                'description_ru' => 'Полная совместимость с Canon, а также совместима в мануальным режиме для камер Sony и Nikon',
                'description_en' => 'Fully compatible with Canon, and also compatible in manual mode for Sony and Nikon cameras',
                'additionals' => [
                    'Cофтбокс',
                    'Синхронизатор Godox X PRO',
                    'Монопод',
                ],
                'image' => '67.png',
            ],
            GoodEnum::GODOX_V860_FLASH->name => [
                'name_ru' => GoodEnum::GODOX_V860_FLASH->value,
                'name_en' => 'Godox V860 Flash',
                'cost' => 3000,
                'damage_cost' => 100000,
                'description_ru' => 'Полная совместимость с Sony',
                'description_en' => 'Fully compatible with Sony',
                'additionals' => [
                    'Cофтбокс',
                    'Синхронизатор Godox X PRO',
                    'Монопод',
                ],
                'image' => '61.png',
            ],
            GoodEnum::NANLITE_DJEDAIKA_30CM->name => [
                'name_ru' => GoodEnum::NANLITE_DJEDAIKA_30CM->value,
                'name_en' => 'Nanlite Jedi 30cm',
                'cost' => 3000,
                'damage_cost' => 50000,
                'description_ru' => '"Мощность: 6 Вт Цветовая температура: 2700−7500K Вес: 260гр. Время зарядки: 2,5ч Время работы: 100% мощности :~65 минут; Длина 0.3 м"',
                'description_en' => '"Power: 6 W Color temperature: 2700−7500K Weight: 260g. Charging time: 2.5 hours Operating time: 100% power: ~65 minutes; Length 0.3 m"',
                'additionals' => [],
                'image' => '43.png',
            ],
            GoodEnum::APUTURE_AMARAN_P60C->name => [
                'name_ru' => GoodEnum::APUTURE_AMARAN_P60C->value,
                'name_en' => 'Aputure Amaran p60c',
                'cost' => 5000,
                'damage_cost' => 200000,
                'description_ru' => '"Полная регулировка RGB Цветовая температура, К2500 - 7500 Мощность диодов, Вт 60 В комплект входит софтбокс, соты"',
                'description_en' => '"Fully adjustable RGB Color temperature, K2500 - 7500 Diode power, W 60 The kit includes a softbox, honeycombs"',
                'additionals' => [
                    'Стойка godox',
                    '2 аккумулятора NPF 970 для беспроводной зарядки',
                ],
                'image' => '39.png',
            ],
        ];
    }

    private function sound(): array
    {
        return [
            GoodEnum::DJI_MIC_DUO->name => [
                'name_ru' => GoodEnum::DJI_MIC_DUO->value,
                'name_en' => 'Dji mic duo',
                'cost' => 5000,
                'damage_cost' => 160000,
                'description_ru' => 'Диапазон эффективной передачи 250 м 2-канальная запись Встроенное хранилище до 14 часов Время работы батареи 15 часов',
                'description_en' => '250m effective transmission range 2-channel recording Built-in storage up to 14 hours Battery life 15 hours',
                'additionals' => [],
                'image' => '88.png',
            ],
            GoodEnum::DJI_MIC_2_DUO->name => [
                'name_ru' => GoodEnum::DJI_MIC_2_DUO->value,
                'name_en' => 'Dji Mic 2 duo',
                'cost' => 6000,
                'damage_cost' => 200000,
                'description_ru' => 'Новинка 2024 года ! Диапазон эффективной передачи 250 м 2-канальная запись 32-битная запись Встроенное хранилище до 14 часов Время работы батареи 15 часов',
                'description_en' => 'New for 2024! Effective transmission range 250m 2-channel recording 32-bit recording Built-in storage up to 14 hours Battery life 15 hours',
                'additionals' => [],
                'image' => '89.png',

            ],
            GoodEnum::HOLLYLAND_LARK_MAX->name => [
                'name_ru' => GoodEnum::HOLLYLAND_LARK_MAX->value,
                'name_en' => 'Hollyland Lark Max',
                'cost' => 5000,
                'damage_cost' => 160000,
                'description_ru' => 'Диапазон эффективной передачи 250 м 2-канальная запись Звук студийного качества Встроенное хранилище до 14 часов Время работы батареи 8 часов',
                'description_en' => '250m effective transmission range 2-channel recording Studio quality sound Built-in storage up to 14 hours Battery life 8 hours',
                'additionals' => [],
                'image' => '90.png',
            ],
            GoodEnum::RODE_GO_2->name => [
                'name_ru' => GoodEnum::RODE_GO_2->value,
                'name_en' => 'Rode go 2',
                'cost' => 4000,
                'damage_cost' => 150000,
                'description_ru' => 'Диапазон эффективной передачи 200м 2-канальная запись Встроенное хранилище до 24 часов Время работы батареи 7 часов',
                'description_en' => '200m effective transmission range 2-channel recording Built-in storage up to 24 hours Battery life 7 hours',
                'additionals' => ['Переходник на телефон'],
                'image' => '87.png',
            ],
            GoodEnum::BOYA_WM4_PRO_K2->name => [
                'name_ru' => GoodEnum::BOYA_WM4_PRO_K2->value,
                'name_en' => 'Boya wm4 pro k2',
                'cost' => 2000,
                'damage_cost' => 80000,
                'description_ru' => 'Двухканальный Беспроводной Приёмник Цифровой 2,4ГГц Диапазон Частот Всенаправленный петличный микрофон Рабочий диапазон 60 м (без препятствий) Питание от двух батареек типа ААА (в комплект не входит)',
                'description_en' => 'Dual Channel Wireless Receiver Digital 2.4GHz Frequency Range Omnidirectional Lavalier Microphone Operating Range 60m (no obstacles) Powered by two AAA batteries (not included)',
                'additionals' => [],
                'image' => '60.png',
            ],
            GoodEnum::SARAMONIC_UWMIC9_TX_TX_RX->name => [
                'name_ru' => GoodEnum::SARAMONIC_UWMIC9_TX_TX_RX->value,
                'name_en' => 'Saramonic UwMic9 Tx+TX + Rx',
                'cost' => 2000,
                'damage_cost' => 200000,
                'description_ru' => 'Диапазон передачи: 514MHz - 596MHz Группы каналов: A,B Диапазон записи: 40 Гц-18 кГц (+/- 3 дБ) Дальность действия: 100 м (без препятствий); до 60 м (в помещении) Питание: Две батарейки типа AA (в комплект не входит) Время работы 1-2 часа',
                'description_en' => 'Transmitting range: 514MHz - 596MHz Channel groups: A,B Recording range: 40Hz-18kHz (+/- 3dB) Range: 100m (no obstacles); up to 60 m (indoors) Power: Two AA batteries (not included) Operating time 1-2 hours',
                'additionals' => [],
                'image' => '59.png',
            ],
            GoodEnum::MICROPHONE_RODE_VIDEOMIC_PRO->name => [
                'name_ru' => GoodEnum::MICROPHONE_RODE_VIDEOMIC_PRO->value,
                'name_en' => 'Rode videomic pro microphone',
                'cost' => 2000,
                'damage_cost' => 100000,
                'description_ru' => 'Конденсаторный микрофон телевещательного качества Сверхлегкий (85 г), сверхкомпактный (15 см длиной) Питание от 9В батарейки (свыше 70 часов)',
                'description_en' => 'Broadcast quality condenser microphone Ultra-light (85g), ultra-compact (15cm long) Powered by 9V battery (over 70 hours)',
                'additionals' => [],
                'image' => '56.png',
            ],
            GoodEnum::WALKIE_TALKIE_LUITON_316->name => [
                'name_ru' => GoodEnum::WALKIE_TALKIE_LUITON_316->value,
                'name_en' => 'Walkie talkie luiton 316',
                'cost' => 1000,
                'damage_cost' => 20000,
                'description_ru' => 'радиосвязь на расстоянии до 6 км! Литиевая батарея емкостью 1500 мАч обеспечивает напряженную работу радиостанции в течение 8 часов. Динамики повышенной мощности (1000 мВт) обеспечивают громкий и разборчивый звук.',
                'description_en' => 'radio communication at a distance of up to 6 km! A 1500 mAh lithium battery ensures the radio works hard for 8 hours. High-power speakers (1000 mW) deliver loud, clear sound.',
                'additionals' => [],
                'image' => null,

            ],
            GoodEnum::AUDIO_RECORDER_ZOOM_H6->name => [
                'name_ru' => GoodEnum::AUDIO_RECORDER_ZOOM_H6->value,
                'name_en' => 'Zoom H6 Recorder',
                'cost' => 4500,
                'damage_cost' => 180000,
                'description_ru' => 'Одновременная запись на шесть дорожек. 4 микрофонных/линейных входа с комбинированными разъемами XLR/TRS. Прямая запись на SD, SDHC и SDXC карты емкостью до 128 ГБ. Запись аудио качеством до 24-бит/96 кГц в BWF-совместимом формате WAV или в различных MP3-форматах. Встроенные эффекты, включающие фильтр обрезки низких частот, компрессор и лимитер. Работа от стандартных алкалиновых батареек типа AA или аккумуляторов NiMH. Более 20 часов работы от четырех алкалиновых батареек.',
                'description_en' => 'Simultaneous recording on six tracks. 4 mic/line inputs with XLR/TRS combo connectors. Direct recording to SD, SDHC and SDXC cards up to 128GB. Record audio quality up to 24-bit/96 kHz in BWF-compatible WAV format or various MP3 formats. Built-in effects including low-cut filter, compressor and limiter. Operates on standard AA alkaline or NiMH batteries. Over 20 hours of operation on four alkaline batteries.',
                'additionals' => [],
                'image' => '91.png',
            ],
        ];
    }

    private function stabilizers(): array
    {
        return [
            GoodEnum::RONIN_RS_2->name => [
                'name_ru' => GoodEnum::RONIN_RS_2->value,
                'name_en' => 'Ronin Rs 2',
                'cost' => 10000,
                'damage_cost' => 450000,
                'description_ru' => 'Cтабилизатор массой 1 кг можно установить 4,5 кг. совместим с Black magic 6k pro Возможность сьемки в вертикальном положении',
                'description_en' => 'A stabilizer weighing 1 kg can be installed with a weight of 4.5 kg. compatible with Black magic 6k pro Possibility of shooting in a vertical position',
                'additionals' => [
                    'Raven eye' => 2000,
                    'Ручка' => 1000,
                    'Follow focus' => 1000,
                ],
                'image' => '116.png',
            ],
            GoodEnum::RONIN_SC->name => [
                'name_ru' => GoodEnum::RONIN_SC->value,
                'name_en' => 'Ronin Sc',
                'cost' => 6000,
                'damage_cost' => 200000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '38.png',
            ],
            GoodEnum::OSMO_4->name => [
                'name_ru' => GoodEnum::OSMO_4->value,
                'name_en' => 'Osmo 4',
                'cost' => 3000,
                'damage_cost' => 100000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '117.png',
            ],
        ];
    }

    private function batteries(): array
    {
        return [
            GoodEnum::SONY_NP_FZ100->name => [
                'name_ru' => GoodEnum::SONY_NP_FZ100->value,
                'name_en' => 'Sony NP-fz100',
                'cost' => 1000,
                'damage_cost' => 50000,
                'additional_cost' => 500,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '98.png',
            ],
            GoodEnum::SONY_NP_FW50->name => [
                'name_ru' => GoodEnum::SONY_NP_FW50->value,
                'name_en' => 'Sony NP-fw50',
                'cost' => 1000,
                'damage_cost' => 35000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::FUJIFILM_NP_W126->name => [
                'name_ru' => GoodEnum::FUJIFILM_NP_W126->value,
                'name_en' => 'Fujifilm Np-w126',
                'cost' => 1000,
                'damage_cost' => 40000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::FUJIFILM_NP_W235->name => [
                'name_ru' => GoodEnum::FUJIFILM_NP_W235->value,
                'name_en' => 'Fujifilm Np-w235',
                'cost' => 1000,
                'damage_cost' => 40000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::CANON_LP_E6NH->name => [
                'name_ru' => GoodEnum::CANON_LP_E6NH->value,
                'name_en' => 'Canon LP e6Nh',
                'cost' => 1000,
                'damage_cost' => 50000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::FUJIFILM_NP_W235_DUMMY_BATTERY->name => [
                'name_ru' => GoodEnum::FUJIFILM_NP_W235_DUMMY_BATTERY->value,
                'name_en' => 'Dummy battery Fujifilm Np-w235',
                'cost' => 1000,
                'damage_cost' => 30000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '101.png',
            ],
            GoodEnum::SONY_NP_FZ100_DUMMY_BATTERY->name => [
                'name_ru' => GoodEnum::SONY_NP_FZ100_DUMMY_BATTERY->value,
                'name_en' => 'Dummy battery Sony NP-fz100',
                'cost' => 1000,
                'damage_cost' => 30000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '100.png',
            ],
            GoodEnum::BOYA_IPHONE_ADAPTER_CABLE->name => [
                'name_ru' => GoodEnum::BOYA_IPHONE_ADAPTER_CABLE->value,
                'name_en' => 'Boya iPhone adapter cord',
                'cost' => 500,
                'damage_cost' => 15000,
                'additional_cost' => 0,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::NP_FZ100_SONY_CHARGER->name => [
                'name_ru' => GoodEnum::NP_FZ100_SONY_CHARGER->value,
                'name_en' => 'Charging block NP-fz100 Sony',
                'cost' => 1000,
                'damage_cost' => 15000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::NP_FW50_SONY_CHARGER->name => [
                'name_ru' => GoodEnum::NP_FW50_SONY_CHARGER->value,
                'name_en' => 'Charging unit NP-fw50 Sony',
                'cost' => 1000,
                'damage_cost' => 15000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::GOPRO_BATTERIES->name => [
                'name_ru' => GoodEnum::GOPRO_BATTERIES->value,
                'name_en' => 'Go pro batteries',
                'cost' => 1000,
                'damage_cost' => 40000,
                'additional_cost' => 1000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::NPF_970_SET_OF_12->name => [
                'name_ru' => GoodEnum::NPF_970_SET_OF_12->value,
                'name_en' => 'Npf 970 (12 pcs)',
                'cost' => 1500,
                'damage_cost' => 60000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '97.png',
            ],
            GoodEnum::NPF_750_SET_OF_1->name => [
                'name_ru' => GoodEnum::NPF_750_SET_OF_1->value,
                'name_en' => 'Npf 750 (1 piece)',
                'cost' => 1000,
                'damage_cost' => 40000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::SMALL_RIG_V_MOUNT_99WH->name => [
                'name_ru' => GoodEnum::SMALL_RIG_V_MOUNT_99WH->value,
                'name_en' => 'Small Rig V mount 99wh',
                'cost' => 2500,
                'damage_cost' => 100000,
                'additional_cost' => 2000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '99.png',
            ],
            GoodEnum::AIR_2_BATTERIES->name => [
                'name_ru' => GoodEnum::AIR_2_BATTERIES->value,
                'name_en' => 'Batteries for Air 2',
                'cost' => 4000,
                'damage_cost' => 80000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
        ];
    }

    private function drones(): array
    {
        return [
            GoodEnum::DJI_AIR_2->name => [
                'name_ru' => GoodEnum::DJI_AIR_2->value,
                'name_en' => 'Dji Air 2',
                'cost' => 16000,
                'damage_cost' => 600000,
                'description_ru' => 'DJI Mavic Air 2 -  Дрон снабжён камерой с сенсором более высокого разрешения, фирменной технологией передачи сигнала OcuSync, обеспечивает длительность полёта до 34 минут, а также управляется с помощью нового контроллера.  Камера поддерживает видеосъёмку 4К с 60 кадров в секунду. Предусмотрена съёмка в формате HDR как для видео, так и для панорамных фотографий. Кол-во мегапикселей: 48 MP',
                'description_en' => 'DJI Mavic Air 2 - The drone is equipped with a camera with a higher resolution sensor, proprietary OcuSync signal transmission technology, provides a flight duration of up to 34 minutes, and is also controlled using a new controller. The camera supports 4K video recording at 60 frames per second. Shooting in HDR format is provided for both video and panoramic photos. Number of megapixels: 48 MP',
                'additionals' => [
                    'Доп. аккумулятор',
                ],
                'image' => '3.png',
            ],
        ];
    }

    private function dataCards(): array
    {
        return [
            GoodEnum::SANDISK_64GB->name => [
                'name_ru' => GoodEnum::SANDISK_64GB->value,
                'name_en' => 'Sandisk 64gb',
                'cost' => 1000,
                'damage_cost' => 20000,
                'additional_cost' => 1000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '50.png',
            ],
            GoodEnum::SANDISK_128GB_170MB_S->name => [
                'name_ru' => GoodEnum::SANDISK_128GB_170MB_S->value,
                'name_en' => 'Sandisk 128gb 170mb/s',
                'cost' => 1500,
                'damage_cost' => 30000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '49.png',
            ],
            GoodEnum::MICRO_SANDISK_64_GB->name => [
                'name_ru' => GoodEnum::MICRO_SANDISK_64_GB->value,
                'name_en' => 'Micro sandisk 64 gb',
                'cost' => 500,
                'damage_cost' => 18000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,

            ],
            GoodEnum::SONY_256GB_UHS_2->name => [
                'name_ru' => GoodEnum::SONY_256GB_UHS_2->value,
                'name_en' => 'Sony 256gb UHS-2',
                'cost' => 2500,
                'damage_cost' => 100000,
                'additional_cost' => 2500,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '48.png',
            ],
            GoodEnum::TOUGH_80GB_G_800_MBS->name => [
                'name_ru' => GoodEnum::TOUGH_80GB_G_800_MBS->value,
                'name_en' => 'Tough 80Gb G 800 mbs',
                'cost' => 2500,
                'damage_cost' => 130000,
                'additional_cost' => 3000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '47.png',
            ],
            GoodEnum::SAMSUNG_EVO_PLUS_64GB->name => [
                'name_ru' => GoodEnum::SAMSUNG_EVO_PLUS_64GB->value,
                'name_en' => 'Samsung Evo plus 64gb',
                'cost' => 500,
                'damage_cost' => 15000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '51.png',
            ],
            GoodEnum::SAMSUNG_EVO_PLUS_256GB->name => [
                'name_ru' => GoodEnum::SAMSUNG_EVO_PLUS_256GB->value,
                'name_en' => 'Samsung Evo plus 256gb',
                'cost' => 1000,
                'damage_cost' => 25000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::MICRO_64GB_ADATA->name => [
                'name_ru' => GoodEnum::MICRO_64GB_ADATA->value,
                'name_en' => 'Micro 64gb Adata',
                'cost' => 500,
                'damage_cost' => 15000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::SAMSUNG_T7_1TB->name => [
                'name_ru' => GoodEnum::SAMSUNG_T7_1TB->value,
                'name_en' => 'Samsung T7 1tb',
                'cost' => 3000,
                'damage_cost' => 80000,
                'additional_cost' => 3000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '94.png',
            ],
        ];
    }

    private function cages(): array
    {
        return [
            GoodEnum::UURIG_HAND_FOR_SONY_A7_3->name => [
                'name_ru' => GoodEnum::UURIG_HAND_FOR_SONY_A7_3->value,
                'name_en' => 'UUrig + hand for Sony a7 3',
                'cost' => 1500,
                'damage_cost' => 35000,
                'additional_cost' => 1500,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::UURIG_FOR_FUJIFILM_T4->name => [
                'name_ru' => GoodEnum::UURIG_FOR_FUJIFILM_T4->value,
                'name_en' => 'UUrig for Fujifilm T4',
                'cost' => 1000,
                'damage_cost' => 25000,
                'additional_cost' => 1000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '113.png',
            ],
            GoodEnum::SMALLRIG_FOR_A7C->name => [
                'name_ru' => GoodEnum::SMALLRIG_FOR_A7C->value,
                'name_en' => 'Smallrig for A7c',
                'cost' => 1000,
                'damage_cost' => 25000,
                'additional_cost' => 1500,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '113.png',
            ],
            GoodEnum::SMALLRIG_HAND_AND_HANDLE_A6600->name => [
                'name_ru' => GoodEnum::SMALLRIG_HAND_AND_HANDLE_A6600->value,
                'name_en' => 'Smarig + handle and handle a6600',
                'cost' => 1000,
                'damage_cost' => 25000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::TILTA_ADVANCED_FX6->name => [
                'name_ru' => GoodEnum::TILTA_ADVANCED_FX6->value,
                'name_en' => 'Tilta Advanced Fx6',
                'cost' => 1500,
                'damage_cost' => 30000,
                'additional_cost' => 3000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::TILTA_ADVANCED_KIT_FX3->name => [
                'name_ru' => GoodEnum::TILTA_ADVANCED_KIT_FX3->value,
                'name_en' => 'Tilta advanced kit Fx3',
                'cost' => 5000,
                'damage_cost' => 180000,
                'additional_cost' => 2500,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
        ];
    }

    private function displays(): array
    {
        return [
            GoodEnum::FEELWORLD_LUT_7_4K_HDMI->name => [
                'name_ru' => GoodEnum::FEELWORLD_LUT_7_4K_HDMI->value,
                'name_en' => 'Feelworld LUT 7 4k HDMI',
                'cost' => 3000,
                'damage_cost' => 135000,
                'description_ru' => 'Яркий и контрастный экран позволяет эффективно работать в любых условиях освещенности: и в яркий солнечный день, и в затемненном помещении. Диагональ экрана 7" и качество изображения DCI 4K (максимум) позволяют увидеть все детали, попавшие в кадр. 2200 Nit. Возможность загрузки Lut',
                'description_en' => 'The bright and contrasting screen allows you to work effectively in any lighting conditions: both on a bright sunny day and in a darkened room. 7" screen diagonal and DCI 4K image quality (maximum) allow you to see all the details caught in the frame. 2200 Nit. Possibility of Lut',
                'additionals' => [
                    'Аккумулятор NPF 970',
                ],
                'image' => '57.png',
            ],
            GoodEnum::LILLIPUT_4K->name => [
                'name_ru' => GoodEnum::LILLIPUT_4K->value,
                'name_en' => 'Lilliput 4K',
                'cost' => 2500,
                'damage_cost' => 100000,
                'description_ru' => 'Оцените все возможности своей камеры при помощи этого 4K монитора. Full HD с разрешением 1920х1200 пикселей и высокой контрастностью 1000:1 передают невероятно красочную и качественную картинку.',
                'description_en' => 'Experience the full capabilities of your camera with this 4K monitor. Full HD with a resolution of 1920x1200 pixels and a high contrast of 1000:1 conveys incredibly colorful and high-quality images.',
                'additionals' => [
                    'Аккумулятор NPF 970',
                ],
                'image' => '58.png',
            ],
            GoodEnum::FEELWORLD_4K_ULTRA->name => [
                'name_ru' => GoodEnum::FEELWORLD_4K_ULTRA->value,
                'name_en' => 'Feelworld 4K ultra',
                'cost' => 4000,
                'damage_cost' => 200000,
                'description_ru' => 'Большой монитор с разрешением 4k c возможностью загрузки LUT. Отлично подойдет как Playback',
                'description_en' => 'Large 4k monitor with LUT loading capability. Perfect as Playback',
                'additionals' => [
                    'Аккумулятор NPF 970',
                ],
                'image' => null,
            ],
        ];
    }

    private function miscellaneous(): array
    {
        return [
            GoodEnum::VIDEOSENDERS_HOLLYLAND_MARS_400S_PRO->name => [
                'name_ru' => GoodEnum::VIDEOSENDERS_HOLLYLAND_MARS_400S_PRO->value,
                'name_en' => 'Video senders Hollyland Mars 400s pro',
                'cost' => 7000,
                'damage_cost' => 250000,
                'description_ru' => 'беспроводная передача AV-сигнала на расстояние до 120 метров с задержкой всего 0,08 с Входы SDI и HDMI Несколько режимов мониторинга',
                'description_en' => 'wireless AV signal transmission up to 120 meters with a latency of only 0.08 s SDI and HDMI inputs Multiple monitoring modes',
                'additionals' => [],
                'image' => '93.png',
            ],
            GoodEnum::TELEPROMPTER_FEELWORLD_TP10->name => [
                'name_ru' => GoodEnum::TELEPROMPTER_FEELWORLD_TP10->value,
                'name_en' => 'Teleprompter Feelworld Tp10',
                'cost' => 4000,
                'damage_cost' => 60000,
                'description_ru' => 'FEELWORLD TP10 - это складной портативный телесуфлер, оснащенный 10-дюймовым стандартным светоделителем, который позволяет четко читать прокручиваемый текст, глядя прямо в камеру, что идеально подходит для видеоблога и прямой трансляции , онлайн-уроки, видеозапись, интервью, видеостудия, новости и презентации.',
                'description_en' => 'FEELWORLD TP10 is a foldable portable teleprompter equipped with a 10" standard beam splitter that allows you to read scrolling text clearly while looking directly into the camera, ideal for vlogging and live broadcasting, online lessons, video recording, interviews, video studio, news and presentations .',
                'additionals' => [],
                'image' => '92.png',
            ],
            GoodEnum::REFLECTOR->name => [
                'name_ru' => GoodEnum::REFLECTOR->value,
                'name_en' => 'Reflector',
                'cost' => 1500,
                'damage_cost' => 30000,
                'description_ru' => 'Отражатель Selens 60х90 см 5 в 1 состоит из пяти отражающих поверхностей: белой, серебряной, золотой, черной, полупрозрачной. Оснащен тремя удобными ручками, что упрощает работу с отражателем.',
                'description_en' => 'Selens reflector 60x90 cm 5 in 1 consists of five reflective surfaces: white, silver, gold, black, translucent. Equipped with three comfortable handles, making it easy to work with the reflector.',
                'additionals' => [],
                'image' => '45.png',
            ],
            GoodEnum::CHROMAKEY_200X150->name => [
                'name_ru' => GoodEnum::CHROMAKEY_200X150->value,
                'name_en' => 'Chroma key 200x150',
                'cost' => 1500,
                'damage_cost' => 30000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '46.png',
            ],
            GoodEnum::SYNCHRONIZER_GODOX_X_PRO->name => [
                'name_ru' => GoodEnum::SYNCHRONIZER_GODOX_X_PRO->value,
                'name_en' => 'Godox X pro synchronizer',
                'cost' => 1500,
                'damage_cost' => 35000,
                'additional_cost' => 1000,
                'description_ru' => 'синхронизатор Godox Xpro-C TTL с функцией Дистанционного управления вспышками',
                'description_en' => 'Godox Xpro-C TTL synchronizer with Remote flash function',
                'additionals' => [],
                'image' => '55.png',
            ],
            GoodEnum::MONOPOD->name => [
                'name_ru' => GoodEnum::MONOPOD->value,
                'name_en' => 'Monopod',
                'cost' => 500,
                'damage_cost' => 15000,
                'additional_cost' => 500,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::COMPENDIUM_SMALLRIG->name => [
                'name_ru' => GoodEnum::COMPENDIUM_SMALLRIG->value,
                'name_en' => 'SmallRig Compendium',
                'cost' => 1000,
                'damage_cost' => 40000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::SMOKE_MACHINE_900W->name => [
                'name_ru' => GoodEnum::SMOKE_MACHINE_900W->value,
                'name_en' => 'Smoke Machine 900watt',
                'cost' => 4000,
                'damage_cost' => 40000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '95.png',
            ],
        ];
    }

    private function softboxes(): array
    {
        return [
            GoodEnum::SOFTBOX_LATERN_90->name => [
                'name_ru' => GoodEnum::SOFTBOX_LATERN_90->value,
                'name_en' => 'Softbox Latern 90',
                'cost' => 3000,
                'damage_cost' => 70000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '109.png',
            ],
            GoodEnum::SOFTBOX_OCTADOME_120->name => [
                'name_ru' => GoodEnum::SOFTBOX_OCTADOME_120->value,
                'name_en' => 'Softbox Octadome 120',
                'cost' => 3000,
                'damage_cost' => 70000,
                'additional_cost' => 1500,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '108.png',
            ],
            GoodEnum::SOFTBOX_LIGHT_DOME_150->name => [
                'name_ru' => GoodEnum::SOFTBOX_LIGHT_DOME_150->value,
                'name_en' => 'Softbox Light Dome 150',
                'cost' => 3000,
                'damage_cost' => 75000,
                'additional_cost' => 2500,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '107.png',
            ],
            GoodEnum::SOFTBOX_GODOX_60_60->name => [
                'name_ru' => GoodEnum::SOFTBOX_GODOX_60_60->value,
                'name_en' => 'Godox Softbox 60/60',
                'cost' => 5000,
                'damage_cost' => 150000,
                'additional_cost' => 1000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::FLASH_SOFTBOX->name => [
                'name_ru' => GoodEnum::FLASH_SOFTBOX->value,
                'name_en' => 'Softbox for flash',
                'cost' => 1000,
                'damage_cost' => 15000,
                'additional_cost' => 1000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
        ];
    }

    private function filters(): array
    {
        return [
            GoodEnum::ND_FREEWELL_67MM->name => [
                'name_ru' => GoodEnum::ND_FREEWELL_67MM->value,
                'name_en' => 'Nd Freewell 67mm',
                'cost' => 2000,
                'damage_cost' => 100000,
                'additional_cost' => 2000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '123.png',
            ],
            GoodEnum::ND_77MM->name => [
                'name_ru' => GoodEnum::ND_77MM->value,
                'name_en' => 'Nd 77 mm',
                'cost' => 1000,
                'damage_cost' => 32000,
                'additional_cost' => 1000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '121.png',
            ],
            GoodEnum::ND_58MM->name => [
                'name_ru' => GoodEnum::ND_58MM->value,
                'name_en' => 'Nd 58mm',
                'cost' => 1000,
                'damage_cost' => 32000,
                'additional_cost' => 1000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '122.png',
            ],
            GoodEnum::ND_72MM->name => [
                'name_ru' => GoodEnum::ND_72MM->value,
                'name_en' => 'Nd 72 mm',
                'cost' => 1000,
                'damage_cost' => 32000,
                'additional_cost' => 1000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => '120.png',
            ],
            GoodEnum::TIFFEN_MIST_FILTER_67MM->name => [
                'name_ru' => GoodEnum::TIFFEN_MIST_FILTER_67MM->value,
                'name_en' => 'Tiffen mist filter 67mm',
                'cost' => 2000,
                'damage_cost' => 50000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::POLARIZED_77MM->name => [
                'name_ru' => GoodEnum::POLARIZED_77MM->value,
                'name_en' => 'Polarized 77mm',
                'cost' => 1000,
                'damage_cost' => 32000,
                'description_ru' => '',
                'description_en' => '',
                'additionals' => [],
                'image' => null,
            ],
        ];
    }

    private function stands(): array
    {
        return [
            GoodEnum::LIGHT_STAND_GODOX_213B->name => [
                'name_ru' => GoodEnum::LIGHT_STAND_GODOX_213B->value,
                'name_en' => 'Godox stand 213b',
                'cost' => 1000,
                'damage_cost' => 25000,
                'additional_cost' => 1000,
                'description_ru' => 'Максимальная высота 213 см Нагрузка 2кг',
                'description_en' => 'Maximum height 213 cm Load capacity 2kg',
                'additionals' => [],
                'image' => '62.png',
            ],
            GoodEnum::LIGHT_STAND_GODOX_380->name => [
                'name_ru' => GoodEnum::LIGHT_STAND_GODOX_380->value,
                'name_en' => 'Godox 380 stand',
                'cost' => 2000,
                'damage_cost' => 35000,
                'additional_cost' => 1000,
                'description_ru' => 'Максимальная высота 380 см Нагрузка 5кг',
                'description_en' => 'Maximum height 380 cm Load capacity 5kg',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::LIGHT_STAND_GODOX_SL->name => [
                'name_ru' => GoodEnum::LIGHT_STAND_GODOX_SL->value,
                'name_en' => 'Godox sl stand',
                'cost' => 1000,
                'damage_cost' => 25000,
                'description_ru' => 'Максимальная высота 200 см Нагрузка 2.5кг',
                'description_en' => 'Maximum height 200 cm Load capacity 2.5kg',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::NO_NAME_LIGHT_STANDS->name => [
                'name_ru' => GoodEnum::NO_NAME_LIGHT_STANDS->value,
                'name_en' => 'Racks no name',
                'cost' => 1000,
                'damage_cost' => 25000,
                'description_ru' => 'Максимальная высота 300 см Нагрузка 2.5кг',
                'description_en' => 'Maximum height 300 cm Load capacity 2.5kg',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::LARGE_NO_NAME_LIGHT_STAND->name => [
                'name_ru' => GoodEnum::LARGE_NO_NAME_LIGHT_STAND->value,
                'name_en' => 'No name stand large',
                'cost' => 1500,
                'damage_cost' => 30000,
                'description_ru' => 'Максимальная высота 380см Нагрузка 4кг',
                'description_en' => 'Maximum height 380cm Load 4kg',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::C_STAND_K2_MEKING->name => [
                'name_ru' => GoodEnum::C_STAND_K2_MEKING->value,
                'name_en' => 'C stand k2 meking',
                'cost' => 2500,
                'damage_cost' => 75000,
                'additional_cost' => 2500,
                'description_ru' => 'Сделаны из хромированной стали, Прочное покрытие делает стойки устойчивыми для любых погодных условий. Минимальная высота: 1450мм/57 Максимальная высота: 3280мм/129 Длина в сложенном состоянии: 1450мм/57 Вес: 7.50kg/16.5lbs Количество секций: 3 Диаметр секций: 25.30.35. 16 Диметр ног: 30 Максимальная нагрузка: 10kg/22lbs Размах ног: 1080мм/43 Длина руки: 1200мм/47 Высота в Г-образном положении: 2200мм/87',
                'description_en' => 'Made from chrome-plated steel, the durable coating makes the stands resistant to all weather conditions. Minimum height: 1450mm/57 Maximum height: 3280mm/129 Folded length: 1450mm/57 Weight: 7.50kg/16.5lbs Number of sections: 3 Diameter of sections: 25.30.35. 16 Leg diameter: 30 Max load: 10kg/22lbs Leg span: 1080mm/43 Arm length: 1200mm/47 Height in L position: 2200mm/87',
                'additionals' => [],
                'image' => '66.png',
            ],
            GoodEnum::TRIPOD_COMAN->name => [
                'name_ru' => GoodEnum::TRIPOD_COMAN->value,
                'name_en' => 'Coman Tripod',
                'cost' => 2500,
                'damage_cost' => 60000,
                'description_ru' => 'Профессиональный алюминиевый видео штатив от Coman Минимальная высота - 56 см Максимальная выоста - 180 см Максимальная нагрузка 10 кг',
                'description_en' => 'Professional aluminum video tripod from Coman Minimum height - 56 cm Maximum height - 180 cm Maximum load 10 kg',
                'additionals' => [],
                'image' => '64.png',
            ],
            GoodEnum::ALUMINUM_TRIPOD->name => [
                'name_ru' => GoodEnum::ALUMINUM_TRIPOD->value,
                'name_en' => 'Aluminium Tripod',
                'cost' => 1500,
                'damage_cost' => 35000,
                'description_ru' => 'Фото штатив с возможностью вертикальной сьемки Максимальная высота штатива 165см Нагрузка 5кг',
                'description_en' => 'Photo tripod with vertical shooting capability Maximum tripod height 165cm Load 5kg',
                'additionals' => [],
                'image' => '65.png',
            ],
            GoodEnum::WEIFENG_TRIPOD->name => [
                'name_ru' => GoodEnum::WEIFENG_TRIPOD->value,
                'name_en' => 'Weifeng Tripod',
                'cost' => 1000,
                'damage_cost' => 25000,
                'description_ru' => 'Максимальная высота съемки, см  170 Максимальная нагрузка, кг 5 Чехол в комплекте',
                'description_en' => 'Maximum shooting height, cm 170 Maximum load, kg 5 Case included',
                'additionals' => [],
                'image' => null,
            ],
            GoodEnum::CONTINENTAL_TRIPOD_DAMAGED->name => [
                'name_ru' => GoodEnum::CONTINENTAL_TRIPOD_DAMAGED->value,
                'name_en' => 'Continental tripod (damaged)',
                'cost' => 500,
                'damage_cost' => 15000,
                'description_ru' => 'Максимальная высота съемки, см  165 Максимальная нагрузка, кг  4.5',
                'description_en' => 'Maximum shooting height, cm 165 Maximum load, kg 4.5',
                'additionals' => [],
                'image' => '63.png',
            ],
        ];
    }

    private function kits(): array
    {
        return [
            GoodEnum::SONY_FX6_V_MOUNT_SET->name => [
                'name_ru' => GoodEnum::SONY_FX6_V_MOUNT_SET->value,
                'name_en' => 'Sony FX6 V-mount kit',
                'cost' => 49990,
                'damage_cost' => 3410000,
                'description_ru' => '-Sony FX6 -Tilta V-mount kit -Sony bp battery -SWIT 220wh V mount / BP 99WH -CFexpress Tough 160gb',
                'description_en' => '-Sony FX6 -Tilta V-mount kit -Sony bp battery -SWIT 220wh V mount / BP 99WH -CFexpress Tough 160gb',
                'additionals' => [
                    'Доп Smallrig 99WH V mount',
                    'Доп Swit 220 WH V mount',
                    'Доп CF express Tough 160 gb',
                ],
                'image' => '6.png',

            ],
            GoodEnum::BLACKMAGIC_6K_PRO_FULL_SET->name => [
                'name_ru' => GoodEnum::BLACKMAGIC_6K_PRO_FULL_SET->value,
                'name_en' => 'Blackmagic 6k pro complete set',
                'cost' => 25000,
                'damage_cost' => 2130000,
                'description_ru' => 'Полный сетап для Black magic 6k pro в набор входит: Blackmagic 6k pro Объектив Sigma 18-35mm/samyang объектив Small Rig Vmount 99wh + родной аккумулятор Клетка Tilta advanced kit с рукояткой Плата V mount/Tilta NPF Терабайт памяти Samsung T7',
                'description_en' => 'Full setup for Black magic 6k pro kit includes: Blackmagic 6k pro Lens Sigma 18-35mm/samyang lens Small Rig Vmount 99wh + original battery Tilta advanced kit cage with handle V mount/Tilta NPF board Terabyte of memory Samsung T7',
                'additionals' => [
                    'Доп Терабайт памяти samsung T7',
                    'Доп V mount 99wh аккумулятор',
                ],
                'image' => '119.png',

            ],
            GoodEnum::APUTURE_300X_LED_LIGHTS_SET->name => [
                'name_ru' => GoodEnum::APUTURE_300X_LED_LIGHTS_SET->value,
                'name_en' => 'Aputure 300x LED Light Kit',
                'cost' => 23000,
                'damage_cost' => 1100000,
                'additional_cost' => 1500,
                'description_ru' => 'Два мощных источника света с мощностью 300 ват 2 софтбокса Lantern 90 2 Стойки Godox 380F',
                'description_en' => 'Two powerful light sources with a power of 300 watts 2 Lantern 90 softboxes 2 Godox 380F stands',
                'additionals' => [],
                'image' => '72.png',
            ],
            GoodEnum::GODOX_SL200IIID_LED_LIGHTS_SET->name => [
                'name_ru' => GoodEnum::GODOX_SL200IIID_LED_LIGHTS_SET->value,
                'name_en' => 'Godox sl200IIID LED lighting kit',
                'cost' => 15000,
                'damage_cost' => 350000,
                'description_ru' => 'Два мощных источника дневного света мощностью 200 ват. Отлично подойдет для сьемок средних масштабов в комплекте два софтбокса, 2 стойки и два источника света с переносной сумкой.',
                'description_en' => 'Two powerful 200 watt daylight sources. Perfect for medium-sized shoots, it comes with two softboxes, two stands and two lights with a carrying case.',
                'additionals' => [],
                'image' => '71.png',
            ],
            GoodEnum::GODOX_SL100BI_LED_LIGHTS_SET->name => [
                'name_ru' => GoodEnum::GODOX_SL100BI_LED_LIGHTS_SET->value,
                'name_en' => 'Godox sl100bi LED lighting kit',
                'cost' => 9000,
                'damage_cost' => 200000,
                'description_ru' => 'Два средне мощных источника света мощностью 100 ват и регулировкой температуры. в комплекте два софтбокса, 2 стойки и два источника света с переносной сумкой.',
                'description_en' => 'Two medium-power light sources with a power of 100 watts and temperature control. Includes two softboxes, 2 stands and two lights with a carrying case.',
                'additionals' => [],
                'image' => '70.png',
            ],
            GoodEnum::NANLITE_FORZA_60C_LED_LIGHTS_SET->name => [
                'name_ru' => GoodEnum::NANLITE_FORZA_60C_LED_LIGHTS_SET->value,
                'name_en' => 'Nanlite Forza 60c LED Light Kit',
                'cost' => 20000,
                'damage_cost' => 900000,
                'description_ru' => 'Комплект из Nanlite forza 60c идеально подойдет для сьемок кино и коммерции и предметной сьемки В комплекте 3 источника света Forza 60c, 3 софтбокса и 3 стойки',
                'description_en' => 'Nanlite forza 60c set is ideal for filming, commercial and product photography Includes 3 Forza 60c light sources, 3 softboxes and 3 stands',
                'additionals' => [],
                'image' => '103.png',

            ],
            GoodEnum::APUTURE_AMARAN_P60C_LED_LIGHTS_SET->name => [
                'name_ru' => GoodEnum::APUTURE_AMARAN_P60C_LED_LIGHTS_SET->value,
                'name_en' => 'Aputure Amaran p60c LED Light Kit',
                'cost' => 15000,
                'damage_cost' => 450000,
                'description_ru' => 'Комплект из  трех панелей Amaran p60c В комплекте 3 панели, 3 софтбокса и 3 стойки',
                'description_en' => 'Amaran p60c three panel set Includes 3 panels, 3 softboxes and 3 stands',
                'additionals' => [],
                'image' => '40.png',
            ],
            GoodEnum::GODOX_TL60_JEDI_LIGHTS_SET->name => [
                'name_ru' => GoodEnum::GODOX_TL60_JEDI_LIGHTS_SET->value,
                'name_en' => 'Godox TL60 Jedi Kit',
                'cost' => 7000,
                'damage_cost' => 200000,
                'description_ru' => 'Комплект из двукх Джедаек Godox TL60',
                'description_en' => 'Set of two Jedi Godox TL60',
                'additionals' => [],
                'image' => '82.png',
            ],
            GoodEnum::NANLITE_30CM_JEDI_LIGHTS_SET->name => [
                'name_ru' => GoodEnum::NANLITE_30CM_JEDI_LIGHTS_SET->value,
                'name_en' => 'Set Jedi Nanlite 30cm',
                'cost' => 5000,
                'damage_cost' => 100000,
                'description_ru' => 'Комплект из двух маленьких Nanlite джедаек',
                'description_en' => 'Set of two small Nanlite Jedi',
                'additionals' => [],
                'image' => '44.png',
            ],
        ];
    }
}
